site_name: Thinking in Blockchain

pages:
- 前言: index.md
- 去中心化(Decentralization): decentralization.md
- Hyperledger(超级账本): hyperledger.md
- Factom(公证通): factom.md
- Ripple(瑞波币): ripple.md
- '周刊':
  - '20180409': 'weekly/20180409.md'
